---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: couchbaseusers.couchbase.com
spec:
  group: couchbase.com
  names:
    categories:
    - all
    - couchbase
    kind: CouchbaseUser
    plural: couchbaseusers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            authDomain:
              pattern: ^local|external$
              type: string
            authSecret:
              type: string
            fullName:
              type: string
          required:
          - authDomain
          type: object
      type: object
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true

