apiVersion: v1
entries:
  couchbase-operator:
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2025-03-19T18:04:05.210435Z"
    description: A Helm chart to deploy the Couchbase Autonomous Operator for easily
      deploying, managing, and maintaining Couchbase Clusters. Couchbase Server is
      a NoSQL document database with a distributed architecture for performance, scalability,
      and availability. It enables developers to build applications easier and faster
      by leveraging the power of SQL with the flexibility of JSON.
    digest: f482c497754d1e5cedbe7061687b6652ae1dd6f667b2c35b880c5c06ccc21702
    home: https://couchbase.com
    icon: https://couchbase-partners.github.io/helm-charts/assets/img/CB_Logomark_220.png
    keywords:
    - couchbase
    - operator
    - database
    - nosql
    - cluster
    - replication
    maintainers:
    - email: cloud-native@couchbase.com
      name: Couchbase Cloud Native Team
    name: couchbase-operator
    sources:
    - https://docs.couchbase.com/operator/current/helm-setup-guide.html
    type: application
    urls:
    - https://github.com/couchbase-partners/helm-charts/releases/download/couchbase-operator-2.80.3/couchbase-operator-2.80.3.tgz
    version: 2.80.3
generated: "2025-03-19T18:04:05.205506Z"
