apiVersion: v1
kind: Service
metadata:
  name: metrics-operator
  namespace: default
  labels:
    app: metrics-operator
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
  selector:
    app.kubernetes.io/name: couchbase-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-operator
  namespace: default
  labels:
    app.couchbase.com/name: metrics-operator
    release: cb-monitoring # Must match the release name of the monitor stack (Would need to be passed as a value)
spec:
  endpoints:
    - port: metrics
      interval: 5s
  fallbackScrapeProtocol: PrometheusText0.0.4
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: metrics-operator