---
{{- if .Values.couchbaseCluster.create -}}
apiVersion: v1
kind: List
items:
{{- range $bucket, $spec := .Values.couchbaseBuckets }}
{{- if typeIs "map[string]interface {}" $spec }}
- apiVersion: couchbase.com/v2
  kind: CouchbaseBucket
  metadata:
    name: {{ default $bucket $spec.name }}
  spec:
{{ toYaml $spec | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
