# This is a basic workflow to help you get started with Actions

name: Publish CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 2.7.x
    # Ignore anything unrelated to a chart release
    paths-ignore:
      - 'charts/couchbase-operator/examples/**'
      - 'assets/**'
      - 'tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"



      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install helm unittest plugin
        run: helm plugin install https://github.com/vbehar/helm3-unittest


      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Lint chart
        run: helm lint charts/couchbase-operator

      - name: Unit test the chart
        run: helm unittest charts/couchbase-operator

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Validate chart install
        run: ct install --chart-dirs $GITHUB_WORKSPACE --charts charts/couchbase-operator

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


